adding validations to avoid duplicate productCategory, and adding fri…
tailorsoft/mantle-shopify pull request #17
Opened 2021-07-27 16:47 UTC by rocha7778

…endly message error

2021-07-28 15:01 UTC, marror7 commented on service/mantle/shopify/ApiServices.xml
> +                <message type="warning">The product category ${productCategoryId} already exist</message>
already exists*

2021-07-28 15:03 UTC, marror7 requested changes

2021-07-28 15:03 UTC, marror7 commented on service/mantle/shopify/ApiServices.xml
> +                <message type="warning">The product category ${productCategoryId} already exist</message>
already exists, please correct

2021-07-28 15:03 UTC, marror7 commented on service/mantle/shopify/ApiServices.xml
> +                if the product category has members those member are added to current category
Those members*

2021-07-28 15:18 UTC, rocha7778 commented on service/mantle/shopify/ApiServices.xml
> +                <message type="warning">The product category ${productCategoryId} already exist</message>
Done

2021-07-28 15:18 UTC, rocha7778 commented on service/mantle/shopify/ApiServices.xml
> +                if the product category has members those member are added to current category
Done

2021-07-29 16:05 UTC, marror7 approved these changes

2021-07-30 13:13 UTC, merged